const APPLICATION_CONSTANTS = {
    KEY_DEVICE_FINGER_PRINT: "Device-Finger-Print",
    KEY_DEVICE_DESCRIPTION: "Device-Description",
    KEY_AUTHENTICATION_TOKEN: "Authentication-Token",
    APP_NAME: "Sahas Smart Studies",
    REGEX_EMAIL: /^[a-zA-Z0-9._%+-]+@(gmail\.com|yahoo\.com|hotmail\.com|icloud\.com)$/,
    EMPTY_VALUE: "--",
    AUTHORITIES: {
        MANAGE_FEATURE_CAROUSEL: "MANAGE_FEATURE_CAROUSEL",
        USE_EMPLOYEE_CORNER: "USE_EMPLOYEE_CORNER",

        MANAGE_COURSES: "MANAGE_COURSES",

        USE_CONTAINER_MANAGE_USERS: "USE_CONTAINER_MANAGE_USERS",
        USE_PAGE_MY_EXPENSES: "USE_PAGE_MY_EXPENSES",
        USE_PAGE_MANAGE_EXAMS: "USE_PAGE_MANAGE_EXAMS",

        USE_ADMIN_CORNER: "USE_ADMIN_CORNER",
        USE_PAGE_MANAGE_BRANCHES: "USE_PAGE_MANAGE_BRANCHES",
        USE_PAGE_MANAGE_STREAMING_DEVICES_REQUESTS: "USE_PAGE_MANAGE_STREAMING_DEVICES_REQUESTS",
        USE_PAGE_FINANCIALS: "USE_PAGE_FINANCIALS",
        USE_PAGE_ANALYTICS: "USE_PAGE_ANALYTICS",
        USE_PAGE_CHAPTERIZATION: "USE_PAGE_CHAPTERIZATION",
        USE_PAGE_COUPON_CODES: "USE_PAGE_COUPON_CODES",

        USE_DEVELOPER_CORNER: "USE_DEVELOPER_CORNER",

        USE_PAGE_USERS: "USE_PAGE_USERS",
        USE_CONTAINER_USER: "USE_CONTAINER_USER",

        READ_USER_BASICS: "READ_USER_BASICS",
        READ_USER_INQUIRIES: "READ_USER_INQUIRIES",
        READ_USER_ENROLLMENTS: "READ_USER_ENROLLMENTS",
        READ_USER_STREAMING_DEVICES: "READ_USER_STREAMING_DEVICES",
        READ_USER_WALLET: "READ_USER_WALLET",
        READ_USER_GLOBAL_NOTES: "READ_USER_GLOBAL_NOTES",
        READ_USER_ROLES: "READ_USER_ROLES",

        MANAGE_OTHER_USERS: "MANAGE_OTHER_USERS",
    },
    RUPEE: " ₹",
};

module.exports = APPLICATION_CONSTANTS;
