const APPLICATION_CONSTANTS = {
    KEY_DEVICE_FINGER_PRINT: "Device-Finger-Print",
    KEY_DEVICE_DESCRIPTION: "Device-Description",
    KEY_AUTHENTICATION_TOKEN: "Authentication-Token",
    APP_NAME: "Sahas Smart Studies",
    REGEX_EMAIL: /^[a-zA-Z0-9._%+-]+@(gmail\.com|yahoo\.com|hotmail\.com|icloud\.com)$/,
    EMPTY_VALUE: "--",
    AUTHORITIES: {
        // User Management
        MANAGE_OTHER_USERS: "MANAGE_OTHER_USERS",
        USE_CONTAINER_MANAGE_USERS: "USE_CONTAINER_MANAGE_USERS",
        USE_PAGE_USERS: "USE_PAGE_USERS",
        USE_CONTAINER_USER: "USE_CONTAINER_USER",
        READ_USER: "READ_USER",
        CREATE_USER: "CREATE_USER",
        UPDATE_USER: "UPDATE_USER",
        WRITE_USER_BASICS: "WRITE_USER_BASICS",
        READ_USER_BASICS: "READ_USER_BASICS",
        READ_USER_INQUIRIES: "READ_USER_INQUIRIES",
        READ_USER_ENROLLMENTS: "READ_USER_ENROLLMENTS",
        READ_USER_STREAMING_DEVICES: "READ_USER_STREAMING_DEVICES",
        READ_USER_DEVICES: "READ_USER_DEVICES",
        READ_USER_WALLET: "READ_USER_WALLET",
        READ_USER_WALLET_TRANSACTIONS: "READ_USER_WALLET_TRANSACTIONS",
        READ_USER_GLOBAL_NOTES: "READ_USER_GLOBAL_NOTES",
        READ_USER_ROLES: "READ_USER_ROLES",
        CREATE_USER_ROLES: "CREATE_USER_ROLES",
        DELETE_USER_ROLES: "DELETE_USER_ROLES",
        READ_USER_ENROLLMENT_COURSES: "READ_USER_ENROLLMENT_COURSES",
        READ_USER_CHAPTERS_TEST_CATALOGUE: "READ_USER_CHAPTERS_TEST_CATALOGUE",

        // Course Management
        MANAGE_COURSES: "MANAGE_COURSES",
        CREATE_COURSE: "CREATE_COURSE",
        UPDATE_COURSE: "UPDATE_COURSE",
        DELETE_COURSE: "DELETE_COURSE",
        READ_COURSE: "READ_COURSE",
        UPDATE_COURSE_VIEW_INDEX: "UPDATE_COURSE_VIEW_INDEX",


        UPDATE_COURSE_SUBJECT: "UPDATE_COURSE_SUBJECT",
        CREATE_COURSE_SUBJECT: "CREATE_COURSE_SUBJECT",
        DELETE_COURSE_SUBJECT: "DELETE_COURSE_SUBJECT",
        UPDATE_COURSE_SUBJECT_VIEW_INDEX: "UPDATE_COURSE_SUBJECT_VIEW_INDEX",
        ASSIGN_COURSE_SUBJECT: "ASSIGN_COURSE_SUBJECT",


        // Course Category
        READ_COURSE_CATEGORY: "READ_COURSE_CATEGORY",
        CREATE_COURSE_CATEGORY: "CREATE_COURSE_CATEGORY",
        DELETE_COURSE_CATEGORY: "DELETE_COURSE_CATEGORY",
        UPDATE_COURSE_CATEGORY_VIEW_INDEX: "UPDATE_COURSE_CATEGORY_VIEW_INDEX",
        READ_COURSE_BY_CATEGORY: "READ_COURSE_BY_CATEGORY",

        // Subject Management
        UPDATE_SUBJECTS: "UPDATE_SUBJECTS",
        READ_SUBJECTS: "READ_SUBJECTS",
        READ_SUBJECTS_CHAPTERS: "READ_SUBJECTS_CHAPTERS",

        // Chapter Management
        CREATE_CHAPTERS: "CREATE_CHAPTERS",
        UPDATE_CHAPTERS: "UPDATE_CHAPTERS",
        DELETE_CHAPTERS: "DELETE_CHAPTERS",
        READ_CHAPTERS: "READ_CHAPTERS",
        READ_CHAPTERS_TEST: "READ_CHAPTERS_TEST",
        READ_CHAPTERS_MEDIA: "READ_CHAPTERS_MEDIA",
        UPDATE_CHAPTERS_VIEW_INDEXES: "UPDATE_CHAPTERS_VIEW_INDEXES",

        // Media Management
        CREATE_MEDIA: "CREATE_MEDIA",
        UPDATE_MEDIA: "UPDATE_MEDIA",
        DELETE_MEDIA: "DELETE_MEDIA",
        READ_MEDIA: "READ_MEDIA",

        // Enrollment Management
        CREATE_ENROLLMENT: "CREATE_ENROLLMENT",
        UPDATE_ENROLLMENT: "UPDATE_ENROLLMENT",
        READ_ENROLLMENT_TRANSACTION: "READ_ENROLLMENT_TRANSACTION",
        READ_ENROLLMENT_COURSE: "READ_ENROLLMENT_COURSE",
        READ_ENROLLMENT_SUMMARY: "READ_ENROLLMENT_SUMMARY",
        CREATE_ENROLLMENT_TRANSACTION: "CREATE_ENROLLMENT_TRANSACTION",
        CREATE_ENROLLMENT_COURSE: "CREATE_ENROLLMENT_COURSE",
        DELETE_ENROLLMENT_COURSE: "DELETE_ENROLLMENT_COURSE",

        // Inquiry Management
        MANAGE_USER_INQUIRIES: "MANAGE_USER_INQUIRIES",
        CREATE_INQUIRY: "CREATE_INQUIRY",
        UPDATE_INQUIRY: "UPDATE_INQUIRY",
        DELETE_INQUIRY: "DELETE_INQUIRY",
        CREATE_INQUIRY_NOTE: "CREATE_INQUIRY_NOTE",
        DELETE_INQUIRY_NOTE: "DELETE_INQUIRY_NOTE",
        READ_INQUIRY_NOTE: "READ_INQUIRY_NOTE",

        // Wallet Management
        CREATE_WALLET_TRANSACTION: "CREATE_WALLET_TRANSACTION",

        // User Device Management
        UPDATE_USER_DEVICE: "UPDATE_USER_DEVICE",

        // Coupon Code Management
        READ_COUPON_CODE: "READ_COUPON_CODE",
        CREATE_COUPON_CODE: "CREATE_COUPON_CODE",
        UPDATE_COUPON_CODE: "UPDATE_COUPON_CODE",
        DELETE_COUPON_CODE: "DELETE_COUPON_CODE",
        CREATE_COUPON_CODE_COURSES: "CREATE_COUPON_CODE_COURSES",
        DELETE_COUPON_CODE_COURSES: "DELETE_COUPON_CODE_COURSES",
        UPDATE_COUPON_CODE_COURSES: "UPDATE_COUPON_CODE_COURSES",

        // Chapter Types Management
        CREATE_CHAPTER_TYPES: "CREATE_CHAPTER_TYPES",
        UPDATE_CHAPTER_TYPES: "UPDATE_CHAPTER_TYPES",
        DELETE_CHAPTER_TYPES: "DELETE_CHAPTER_TYPES",
        UPDATE_CHAPTER_TYPES_VIEW_INDEXES: "UPDATE_CHAPTER_TYPES_VIEW_INDEXES",

        // Role Management
        CREATE_ROLES: "CREATE_ROLES",
        UPDATE_ROLES: "UPDATE_ROLES",
        DELETE_ROLES: "DELETE_ROLES",
        READ_ROLES_AUTHORITIES: "READ_ROLES_AUTHORITIES",
        CREATE_ROLES_AUTHORITIES: "CREATE_ROLES_AUTHORITIES",
        DELETE_ROLES_AUTHORITIES: "DELETE_ROLES_AUTHORITIES",

        // Authority Management
        CREATE_AUTHORITIES: "CREATE_AUTHORITIES",
        DELETE_AUTHORITIES: "DELETE_AUTHORITIES",

        // Feature Carousel
        //MANAGE_FEATURE_CAROUSEL: "MANAGE_FEATURE_CAROUSEL",
        CREATE_CAROUSEL: 'CREATE_CAROUSEL',
        DELETE_CAROUSEL: 'DELETE_CAROUSEL',

        // Dashboard
        MANAGE_DASHBOARD_DIALOG: "MANAGE_DASHBOARD_DIALOG",

        // Page Access
        USE_EMPLOYEE_CORNER: "USE_EMPLOYEE_CORNER",
        USE_ADMIN_CORNER: "USE_ADMIN_CORNER",
        USE_DEVELOPER_CORNER: "USE_DEVELOPER_CORNER",
        USE_PAGE_MY_EXPENSES: "USE_PAGE_MY_EXPENSES",
        USE_PAGE_MANAGE_EXAMS: "USE_PAGE_MANAGE_EXAMS",
        USE_PAGE_MANAGE_BRANCHES: "USE_PAGE_MANAGE_BRANCHES",
        USE_PAGE_MANAGE_STREAMING_DEVICES_REQUESTS: "USE_PAGE_MANAGE_STREAMING_DEVICES_REQUESTS",
        USE_PAGE_FINANCIALS: "USE_PAGE_FINANCIALS",
        USE_PAGE_ANALYTICS: "USE_PAGE_ANALYTICS",
        USE_PAGE_CHAPTERIZATION: "USE_PAGE_CHAPTERIZATION",
        USE_PAGE_COUPON_CODES: "USE_PAGE_COUPON_CODES",
    },
    RUPEE: " ₹",
};

module.exports = APPLICATION_CONSTANTS;
